word_data = {
    "omlette": ("歐姆蛋、煎蛋捲", "Je prépare une omlette pour le petit-déjeuner."),
    "œuf": ("蛋", "J’utilise deux œufs pour cette recette."),
    "lait": ("牛奶", "Ajoute un peu de lait dans le mélange."),
    "sel": ("鹽", "Je mets une pincée de sel."),
    "poivre": ("胡椒", "Ajoute du poivre selon ton goût."),
    "casser": ("打破、打蛋", "Je casse les œufs dans un bol."),
    "ajouter": ("加入", "Il faut ajouter du lait et du sel."),
    "cuillère": ("湯匙", "Utilise une cuillère pour mesurer le lait."),
    "une pincée de": ("一撮（通常指鹽或胡椒）", "Ajoute une pincée de sel."),
    "mélanger": ("攪拌", "Mélange bien les ingrédients."),
    "fourchette": ("叉子", "Utilise une fourchette pour battre les œufs."),
    "chauffer": ("加熱", "Chauffe la poêle avant de verser le mélange."),
    "poêle": ("平底鍋", "Verse le mélange dans la poêle chaude."),
    "huile": ("油", "Ajoute un peu d’huile dans la poêle."),
    "verser": ("倒入", "Verse le mélange d’œufs dans la poêle."),
    "dorée": ("金黃色的", "Fais cuire jusqu’à ce que l’omelette soit dorée."),
    "plier": ("對折", "Plie l’omelette en deux."),
    "server": ("上菜、供應", "Sers l’omelette chaude."),
}
