word_data = {
    "la foi": ("信仰", "Elle a la foi en Dieu."),
    "croire en dieu": ("信上帝", "Beaucoup de gens croient en Dieu."),
    "en lien": ("有連結、相關", "Tout est en lien avec la foi."),
    "connecté": ("連結的", "Je suis connecté à Internet."),
    "la religion": ("宗教", "La religion est importante pour certaines personnes."),
    "le christianisme": ("基督教", "Le christianisme est une religion monothéiste."),
    "l’islam": ("伊斯蘭教", "L’islam a des règles spécifiques."),
    "le judaïsme": ("猶太教", "Le judaïsme est une ancienne religion."),
    "monothéiste": ("一神論的", "Ces trois religions sont monothéistes."),
    "un terme": ("一個詞", "‘Amour’ est un terme très utilisé."),
    "chrétien": ("基督徒", "Il est chrétien."),
    "musulman": ("穆斯林", "Elle est musulmane."),
    "juif": ("猶太人", "Il est juif."),
    "obligatoire": ("強制的", "Le port du casque est obligatoire."),
    "préciser": ("說明清楚", "Peux-tu préciser ta question ?"),
    "essayer": ("嘗試", "Je vais essayer encore une fois."),
    "rigoureux": ("嚴謹的", "Ce professeur est très rigoureux."),
    "improviser": ("即興發揮", "Il aime improviser en classe."),
    "prononcent faux": ("發音錯", "Les élèves prononcent ce mot faux."),
    "une partie du corps": ("身體的一部分", "La main est une partie du corps."),
    "le foi": ("肝臟", "Le foie est un organe important."),  # 注意：la foi（信仰） vs le foie（肝臟）不同詞！
    "intuitif": ("直覺的", "L’enfant est très intuitif."),
    "réellement": ("真正地", "Tu veux réellement apprendre le français ?"),
    "faire semblant": ("假裝", "Il fait semblant de dormir."),
    "la comédie": ("戲劇、演戲", "Elle adore la comédie."),
    "éternuer": ("打噴嚏", "Quand j’ai froid, j’éternue."),
    "pisine": ("（應為 piscine）游泳池", "La piscine est fermée aujourd’hui."),
}
