word_data = {
    "vieille": ("老的（陰性）", "C’est une vieille maison."),
    "femme": ("女人", "La femme parle avec son ami."),
    "verser": ("倒、倒入", "Il va verser du lait dans le bol."),
    "la farine": ("麵粉", "Elle ajoute la farine à la pâte."),
    "un bol": ("一個碗", "Je prends un bol pour faire un gâteau."),
    "casser": ("打破、打碎", "Il va casser les œufs."),
    "mélanger": ("混合、攪拌", "Tu dois bien mélanger la pâte."),
    "la pâte": ("麵糊", "La pâte est prête à cuire."),
    "la poêle": ("平底鍋", "Elle met la crêpe dans la poêle."),
    "sauter": ("跳躍", "Le chat aime sauter sur la table."),
    "rencounter": ("遇見", "Il va rencounter un vieil ami."),
    "un lapin": ("一隻兔子", "Un lapin court dans le jardin."),
    "échapper": ("逃脫", "Le lapin veut échapper au piège."),
    "attraper": ("抓住", "Le chasseur essaie d’attraper le lapin."),
    "soudain": ("突然", "Soudain, il commence à pleuvoir."),
    "le loup": ("狼", "Le loup hurle à la lune."),
    "un cerf": ("一隻雄鹿", "Un cerf traverse la forêt."),
    "une vache": ("一隻母牛", "La vache donne du lait."),
    "un cochon": ("一隻豬", "Le cochon joue dans la boue."),
}
